post_pro/post/urls.py
from django.urls import path
from .views import post_list_and_create, hello_world_view, load_post_data_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_and_create, name='main-board'),   
    path('data/<int:num_post>/', load_post_data_view, name='data'),

     path('hello-world/', hello_world_view, name='hello-world'),
]

post_pro/post_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='posts')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post_pro/post/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body= models.TextField()
    liked = models.ManyToManyField(User, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

post_pro/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    avatar= models.ImageField(default='avatar.png', upload_to='avatars')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"perfil del usuario {self.user.username}"

post_pro/post/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers

from .models import Post
# Create your views here.

def post_list_and_create(request):
    qs = Post.objects.all()
    return render(request, 'post/main.html', {'qs':qs})

def load_post_data_view(request, num_post):
    visible = 3
    upper = num_post
    lower = upper - visible
    size = Post.objects.all().count()

    qs = Post.objects.all()
    data = []
    for obj in qs:
        item = {
            'id' : obj.id,
            'title': obj.title,
            'body': obj.body,
            'liked': True if request.user in obj.liked.all() else False,
            'author': obj.author.user.username, 
        }
        data.append(item)
    return JsonResponse({'data' : data[lower:upper], 'size': size})

def hello_world_view(request):
    return JsonResponse({'text': 'hello World'})

post_pro/profiles/views.py
from django.shortcuts import render

# Create your views here.

post_pro/post/templates/post/main.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
    <script src="{% static 'post/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    Post
{% endblock title %}

{% block content %}
  <!--  {% for obj in qs %}
    {{ obj.title }} - {{ obj.body }} <br>
   {% endfor %} -->
   
   
   <div id='posts-box'>
        <div id="spinner-box"  class="text-center">
            <div class="spinner-border" role="status"></div>
        </div>
   </div>
   <div class="text-center mb-3" id="end-box">
       <button class="btn btn-primary" id="load-btn">Ver más</button>
   </div>
{% endblock content %}
    

post_pro/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="icon" type="image/png" href=""/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- dropzone -->
    <link rel="stylesheet" href="">
    <script src="" defer></script>

    <!-- Custom js -->
    <script src="" defer></script>
    {% block scripts %}
    {% endblock scripts %}

    <title> posts | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </body>
</html>

post_pro/templates/navbar.html
{% url 'posts:main-board' as path_to_home %}
{% url 'profiles:my-profile' as path_to_my_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path_to_home}}">Posts-proj</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" aria-current="page" href="{{path_to_home}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">My Profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>